--[[

	This file is part of 'Masque: Onyx', an add-on for World of Warcraft. For bug reports,
	documentation and license information, please visit https://github.com/SFX-WoW/Masque_Onyx.

	* File...: Skins.lua
	* Author.: StormFX

	Onyx Skins

]]

local Masque = LibStub and LibStub("Masque", true)
if not Masque then return end

local _, Core = ...

----------------------------------------
-- Internal
---

local L = Core.Locale

----------------------------------------
-- Locals
---

local API_VERSION = 110207

-- Skin Info
local Version = "@project-version@"
local Websites = {
	"https://github.com/SFX-WoW/Masque_Onyx",
	"https://www.curseforge.com/wow/addons/masque-onyx",
	"https://addons.wago.io/addons/masque-onyx",
	"https://www.wowinterface.com/downloads/info8900",
}

local PATH_BACKDROP = [[Interface\AddOns\Masque\Textures\Backdrop\]]

local PATH_BASE = [[Interface\AddOns\Masque_Onyx\Textures\Base\]]
local PATH_GLOW = PATH_BASE.."Glow"

local PATH_CLASSIC = [[Interface\AddOns\Masque_Onyx\Textures\Classic\]]
local PATH_ARROW = PATH_CLASSIC.."Arrow"

----------------------------------------
-- Onyx
---

Masque:AddSkin("Onyx", {
	API_VERSION = API_VERSION,
	Shape = "Square",

	-- [ Info ]
	Author = "StormFX",
	Description = L["A dark skin with slightly rounded corners."],
	Discord = "https://discord.gg/7MTWRgDzz8",
	Version = Version,
	Websites = Websites,

	-- [ UI ]
	Group = "Onyx",
	Order = 1,

	-- [ Skin ]
	-- Mask = nil,
	Backdrop = {
		Texture = PATH_BACKDROP.."Action",
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "BACKGROUND",
		-- DrawLevel = -1,
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseColor = nil,
		Item = {
			Texture = PATH_BACKDROP.."Item",
			-- TexCoords = {0, 1, 0, 1},
			-- Color = {1, 1, 1, 1},
			-- BlendMode = "BLEND",
			-- DrawLayer = "BACKGROUND",
			-- DrawLevel = -1,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
			-- UseColor = nil,
		},
		Pet = {
			Texture = PATH_BACKDROP.."Pet",
			-- TexCoords = {0, 1, 0, 1},
			-- Color = {1, 1, 1, 1},
			-- BlendMode = "BLEND",
			-- DrawLayer = "BACKGROUND",
			-- DrawLevel = -1,
			Width = 32,
			Height = 32,
			-- Point = "CENTER",
			-- RelPoint = "CENTER",
			-- OffsetX = 0,
			-- OffsetY = 0,
			-- SetAllPoints = nil,
			-- UseColor = nil,
		},
	},
	Icon = {
		Texture = [[Interface\Icons\INV_Misc_Bag_08]], -- SlotIcon
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1}, -- SlotIcon
		-- BlendMode = "BLEND", -- SlotIcon
		Width = 32,
		Height = 32,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	SlotIcon = "Icon",
	Shadow = {
		Texture = PATH_BASE.."Shadow",
		-- TexCoords = {0, 1, 0, 1},
		Color = {0, 0, 0, 0.8},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = -1,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	Normal = {
		Texture = PATH_BASE.."Frame",
		-- EmptyTexture = nil,
		-- TexCoords = {0, 1, 0, 1},
		-- EmptyCoords = {0, 1, 0, 1},
		Color = {1, 1, 1, 1},
		-- EmptyColor = {1, 1, 1, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseStates = nil,
	},
	-- Disabled = Default.Disabled,
	Pushed = {
		-- Texture = [[Interface\Buttons\UI-Quickslot-Depress]],
		-- TexCoords = {0, 1, 0, 1},
		Color = {0, 0, 0, 0.5},
		BlendMode = "BLEND",
		DrawLayer = "BORDER",
		DrawLevel = 1,
		Width = 36,
		Height = 36,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		UseColor = true,
	},
	Flash = {
		-- Texture = [[Interface\Buttons\UI-Quickslot-Depress]],
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 0, 0, 0.4},
		BlendMode = "ADD",
		DrawLayer = "BORDER",
		DrawLevel = 0,
		Width = 36,
		Height = 36,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		UseColor = true,
	},
	Checked = {
		Texture = PATH_GLOW,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0, 0.7, 0.9, 0.7},
		BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	SlotHighlight = "Checked",
	Border = {
		Texture = PATH_GLOW,
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	DebuffBorder = "Border",
	EnchantBorder = "Border",
	IconBorder = "Border",
	Gloss = {
		Texture = PATH_BASE.."Gloss",
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 1, 1, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	NewAction = {
		-- Atlas = "Bags-NewItem",
		-- UseAtlasSize = false,
		Texture = PATH_GLOW,
		Color = {1, 1, 0.8, 1},
		BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 1,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	SpellHighlight = "NewAction",
	UpgradeIcon = {
		Atlas = "Bags-GreenArrow",
		-- UseAtlasSize = false, -- true
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		DrawLevel = 2,
		Width = 15,
		Height = 16,
		Point = "TOPLEFT",
		RelPoint = "TOPLEFT",
		OffsetX = 3,
		OffsetY = -3,
		-- SetAllPoints = nil,
	},
	IconOverlay = {
		-- Atlas = "AzeriteIconFrame",
		-- UseAtlasSize = false,
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 1,
		Width = 36,
		Height = 36,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	IconOverlay2 = {
		-- Atlas = "ConduitIconFrame-Corners",
		-- UseAtlasSize = false,
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 2,
		Width = 36,
		Height = 36,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	NewItem = {
		-- Atlas = "Bags-Glow-White",
		-- UseAtlasSize = false,
		Texture = PATH_GLOW,
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		BlendMode = "ADD",
		DrawLayer = "OVERLAY",
		DrawLevel = 2,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	QuestBorder = {
		Border = PATH_BASE.."Quest",
		Texture = PATH_GLOW,
		Color = {1, 0.8, 0, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 2,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	ContextOverlay = {
		-- Texture = nil,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0, 0, 0, 0.7},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 4,
		Width = 36,
		Height = 36,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = true,
		UseColor = true,
	},
	SearchOverlay = "ContextOverlay",
	JunkIcon = {
		Atlas = "Bags-JunkCoin",
		-- UseAtlasSize = false, -- true
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 3,
		Width = 16,
		Height = 16,
		Point = "BOTTOMLEFT",
		RelPoint = "BOTTOMLEFT",
		OffsetX = 3,
		OffsetY = 3,
		-- SetAllPoints = nil,
	},
	Name = {
		-- JustifyH = "CENTER",
		-- JustifyV = "BOTTOM",
		-- DrawLayer = "OVERLAY",
		-- Width = 36,
		-- Height = 0,
		-- Anchor = "Icon",
		-- Point = "BOTTOM",
		-- RelPoint = "BOTTOM",
		-- OffsetX = 0,
		OffsetY = 3,
	},
	Duration = {
		-- JustifyH = "CENTER",
		-- JustifyV = "TOP",
		-- DrawLayer = "OVERLAY",
		-- Width = 36,
		-- Height = 0,
		-- Anchor = "Icon",
		-- Point = "TOP",
		-- RelPoint = "BOTTOM",
		-- OffsetX = 0,
		OffsetY = -3,
	},
	Highlight = {
		Texture = PATH_GLOW,
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 1, 1, 0.4},
		BlendMode = "ADD",
		-- DrawLayer = "HIGHLIGHT",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseColor = nil,
	},
	HotKey = {
		-- JustifyH = "RIGHT",
		-- JustifyV = "TOP",
		-- DrawLayer = "OVERLAY",
		-- Width = 36,
		-- Height = 0,
		-- Anchor = "Icon",
		-- Point = "TOPRIGHT",
		-- RelPoint = "TOPRIGHT",
		OffsetX = -3,
		OffsetY = -3,
	},
	Count = {
		-- JustifyH = "RIGHT",
		-- JustifyV = "BOTTOM",
		-- DrawLayer = "OVERLAY",
		-- Width = 0,
		-- Height = 0,
		-- Anchor = "Icon",
		-- Point = "BOTTOMRIGHT",
		-- RelPoint = "BOTTOMRIGHT",
		OffsetX = -3,
		OffsetY = 3,
	},
	-- [ AutoCastShine (Classic) ]
	AutoCastable = {
		Texture = [[Interface\Buttons\UI-AutoCastableOverlay]],
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 1,
		Width = 54,
		Height = 54,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	AutoCastShine = {
		Width = 27,
		Height = 27,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		OffsetX = 1,
		OffsetY = -1,
		-- SetAllPoints = nil,
	},
	-- [ AutoCastOverlay (Retail) ]
	-- AutoCast_Frame = Default.AutoCast_Frame,
	-- AutoCast_Shine = Default.AutoCast_Shine,
	AutoCast_Mask = {
		-- Atlas = "UI-HUD-ActionBar-PetAutoCast-Mask",
		-- UseAtlasSize = false,
		Texture = [[Interface\AddOns\Masque\Textures\Square\AutoCast-Mask]],
		-- TexCoords = {0, 1, 0, 1},
		Width = 26,
		Height = 26,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	AutoCast_Corners = {
		Atlas = "UI-HUD-ActionBar-PetAutoCast-Corners",
		-- seAtlasSize = false,
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 1,
		Width = 31,
		Height = 31,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = true,
	},
	-- [ Cooldowns ]
	Cooldown = {
		Texture = [[Interface\AddOns\Masque\Textures\Square\Mask]],
		EdgeTexture = [[Interface\AddOns\Masque\Textures\Modern\Edge]],
		-- PulseTexture = [[Interface\Cooldown\star4]],
		Color = {0, 0, 0, 0.7},
		Width = 28,
		Height = 28,
		Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	ChargeCooldown = {
		EdgeTexture = [[Interface\AddOns\Masque\Textures\Square\Edge]],
		-- PulseTexture = [[Interface\Cooldown\star4]],
		Width = 26,
		Height = 26,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	-- [ SpellAlerts ]
	SpellAlert = {
		Width = 34,
		Height = 34,
		AltGlow = {
			Height = 43,
			Width = 43,
		},
		Classic = {
			Height = 28,
			Width = 28,
		},
		Modern = {
			Height = 28,
			Width = 28,
		},
		["Modern-Lite"] = {
			Height = 31,
			Width = 31,
		},
	},
	AssistedCombatHighlight = {
		Width = 43,
		Height = 43,
	},
})

----------------------------------------
-- Onyx Classic
---

Masque:AddSkin("Onyx Classic", {
	-- API_VERSION = Template.API_VERSION,
	-- Shape = Template.Shape,
	Template = "Onyx",

	-- [ Info ]
	-- Author = Template.Author,
	Description = L["The classic Onyx with arrow indicators."],
	-- Discord = Template.Discord,
	-- Version = Template.Version,
	-- Websites = Template.Websites,

	-- [ UI ]
	-- Group = Template.Group,
	Order = 2,
	Title = "Classic",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = PATH_CLASSIC.."Frame",
		-- EmptyTexture = nil,
		-- TexCoords = {0, 1, 0, 1},
		-- EmptyCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- EmptyColor = {1, 1, 1, 0.5},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseStates = nil,
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	Checked = {
		Texture = PATH_ARROW,
		-- TexCoords = {0, 1, 0, 1},
		Color = {0, 0.7, 0.9, 0.7},
		BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	-- Gloss = Template.Gloss,
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay = Template.IconOverlay,
	-- IconOverlay2 = Template.IconOverlay2,
	-- NewItem = Template.NewItem,
	-- QuestBorder = Template.QuestBorder,
	-- ContextOverlay = Template.ContextOverlay,
	-- SearchOverlay = Template.SearchOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Name = Template.Name,
	-- Duration = Template.Duration,
	Highlight = {
		Texture = PATH_ARROW,
		-- TexCoords = {0, 1, 0, 1},
		Color = {1, 1, 1, 0.4},
		BlendMode = "ADD",
		-- DrawLayer = "HIGHLIGHT",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseColor = nil,
	},
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
	-- AutoCastable = Template.AutoCastable,
	-- AutoCastShine = Template.AutoCastShine,
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- SpellAlert = Template.SpellAlert,
	-- AssistedCombatHighlight = Template.AssistedCombatHighlight,
})
